### ISSUE TITLE
Question about RTT Count & RPM value

### ISSUE THREAD

**Issue by richb-hanover** [hawkinsw/goresponsiveness#8]
```
When networkQuality RPM calculation _does_ work, it shows something like this:

√ goresponsiveness % docker run goresp
03-17-2022 14:09:52 UTC Go Responsiveness to mensura.cdn-apple.com:443...
Download:  26.405 Mbps (  3.301 MBps, 12 parallel connections)
Upload:    21.031 Mbps (  2.629 MBps, 20 parallel connections)
Total RTTs measured: 10
RPM:    76
```
But... it's surprising that it's showing only 10 RTT's and/or an RPM of 76. Could there be an error computing these variables? I would have expected my RPM value to be somewhere between 500 & 1500 - that's where it usually comes out with Apple's networkQuality tool.

```
# Running Apple's networkQuality on a Parallels VM of macOS 12.3
richb@Mac-2 ~ % networkQuality -v
==== SUMMARY ====
Upload capacity: 22.705 Mbps
Download capacity: 27.391 Mbps
Upload flows: 20
Download flows: 12
Responsiveness: Medium (513 RPM)
Base RTT: 23
Start: 3/17/22, 6:20:35 PM
End: 3/17/22, 6:20:52 PM
OS Version: Version 12.3 (Build 21E230)
```

**Comment by hawkinsw** [comment]
This is a great question -- I am working with the draft authors to determine if/how calculations of RPM is done. Their work is a little subtle. At this point I am very pleased that the Go implementation of the saturation reliably matches theirs. In other words, we seem (and your results confirm this) to be able to match their throughput values during saturation. 

I hope that this makes sense. More importantly, can you confirm that your saturated throughout is similar to what `networkQaulity` calculates?

**Comment by richb-hanover** [comment]
I proofread the first draft of the RFC, and I agree that the wording is a little squishy. I see you link to a second draft from March 2022. Maybe that's more specific.

I do think the saturation values you compute match my experience. But I have a pretty boring network setup: it's 25mbs up & down fiber service whose speed rarely varies. Plus I have an OpenWrt router with SQM that keeps latency pretty low. The speeds also match the `betterspeedtest.sh` that I wrote as part of [OpenWrtScripts](https://github.com/richb-hanover/OpenWrtScripts)

I will note that I suspect the Wi-Fi may add a lot of latency which might affect my RPM values. I am hoping that someone will create an OpenWrt package that would let me test against my local router (and get RPM values for the laptop-to-router link).

Finally, I got some fun results... I have a VPS in some NOC in Atlanta where I fired up the Go Responsiveness docker file. It shows decent speeds, and pretty respectable RPM values :-) 

But I _still_ don't understand the "Total RTTs Measured" statistic... What does that measure? And is it possible to give some notion of the base latency, as the Apple RPM tool does? Thanks.

```
deploy@atl:~/src/goresponsiveness$ docker run gorun
03-18-2022 01:04:36 UTC Go Responsiveness to mensura.cdn-apple.com:443...
Download: 870.799 Mbps (108.850 MBps), using 12 parallel connections.
Upload:   809.094 Mbps (101.137 MBps), using 24 parallel connections.
Total RTTs measured: 50
RPM:  7097
deploy@atl:~/src/goresponsiveness$ docker run gorun
03-18-2022 01:05:11 UTC Go Responsiveness to mensura.cdn-apple.com:443...
Download: 886.217 Mbps (110.777 MBps), using 12 parallel connections.
Upload:   810.125 Mbps (101.266 MBps), using 24 parallel connections.
Total RTTs measured: 50
RPM:  6548
deploy@atl:~/src/goresponsiveness$ ping mensura.cdn-apple.com
PING mensura.cdn-apple.com(usatl4-vip-bx-003.aaplimg.com (2620:149:a16:f000::3)) 56 data bytes
64 bytes from usatl4-vip-bx-003.aaplimg.com (2620:149:a16:f000::3): icmp_seq=1 ttl=57 time=8.47 ms
64 bytes from usatl4-vip-bx-003.aaplimg.com (2620:149:a16:f000::3): icmp_seq=2 ttl=57 time=0.542 ms
64 bytes from usatl4-vip-bx-003.aaplimg.com (2620:149:a16:f000::3): icmp_seq=3 ttl=57 time=0.636 ms
^C
--- mensura.cdn-apple.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2001ms
rtt min/avg/max/mdev = 0.542/3.215/8.467/3.713 ms
```

**Comment by hawkinsw** [comment]
This feedback is incredibly useful, thank you so much @richb-hanover !! I am doing some prep work for teaching the rest of the night but I will switch back to work on this tomorrow (Friday). I hope to have additional response tomorrow. No matter what, thank you so much for working on this with me, @richb-hanover !!

**Comment by hawkinsw** [comment]
I worked with @cpaasch and @randall today to work through some of the semantics of the RPM calculation. We are tacking toward a solution. I committed a few changes and I'd love to hear your experience with them!

Thanks again for working together on this!

Will

**Comment by richb-hanover** [comment]
Uh oh... Seg fault

```
√ goresponsiveness-1 % ./networkQuality --config mensura.cdn-apple.com --port 443 --path /api/v1/gm/config
03-19-2022 11:27:11 UTC Go Responsiveness to mensura.cdn-apple.com:443...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1226927]

goroutine 255 [running]:
github.com/network-quality/goresponsiveness/ccw.(*ConcurrentWriter).Write(0x12c3a2f, {0xc0007cc370, 0xa2, 0x3})
	/Users/richb/github/goresponsiveness-1/ccw/ccw.go:18 +0x47
crypto/tls.(*Config).writeKeyLog(0xc0004a5e00, {0x12cb63f, 0xc0007c6220}, {0xc0006d9000, 0x20, 0x20}, {0xc0007c6160, 0x20, 0x20})
	/usr/local/Cellar/go/1.17.3/libexec/src/crypto/tls/common.go:1317 +0x1b9
crypto/tls.(*clientHandshakeStateTLS13).establishHandshakeKeys(0xc000a539b8)
	/usr/local/Cellar/go/1.17.3/libexec/src/crypto/tls/handshake_client_tls13.go:367 +0x28d
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc000a539b8)
	/usr/local/Cellar/go/1.17.3/libexec/src/crypto/tls/handshake_client_tls13.go:81 +0x1b3
crypto/tls.(*Conn).clientHandshake(0xc000785c00, {0x1329a18, 0xc0009ef980})
	/usr/local/Cellar/go/1.17.3/libexec/src/crypto/tls/handshake_client.go:219 +0x585
crypto/tls.(*Conn).handshakeContext(0xc000785c00, {0x1329a50, 0xc00019a000})
	/usr/local/Cellar/go/1.17.3/libexec/src/crypto/tls/conn.go:1445 +0x3d1
crypto/tls.(*Conn).HandshakeContext(...)
	/usr/local/Cellar/go/1.17.3/libexec/src/crypto/tls/conn.go:1395
crypto/tls.dial({0x1329a50, 0xc00019a000}, 0xc0000524a0, {0x12c2a3e, 0x3}, {0xc000499420, 0x19}, 0xc0004a5e00)
	/usr/local/Cellar/go/1.17.3/libexec/src/crypto/tls/tls.go:157 +0x3b1
crypto/tls.(*Dialer).DialContext(0x8, {0x1329a50, 0xc00019a000}, {0x12c2a3e, 0x2}, {0xc000499420, 0x0})
	/usr/local/Cellar/go/1.17.3/libexec/src/crypto/tls/tls.go:217 +0x8d
golang.org/x/net/http2.(*Transport).dialTLSWithContext(0x203000, {0x1329a50, 0xc00019a000}, {0x12c2a3e, 0x0}, {0xc000499420, 0x91824b0}, 0x2c)
	/Users/richb/go/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/go115.go:21 +0x4d
golang.org/x/net/http2.(*Transport).dialTLS.func1({0x12c2a3e, 0xc000499420}, {0xc000499420, 0xc0001c0201}, 0x0)
	/Users/richb/go/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/transport.go:620 +0x65
golang.org/x/net/http2.(*Transport).dialClientConn(0x1, {0x1329a50, 0xc00019a000}, {0xc000499420, 0x19}, 0x0)
	/Users/richb/go/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/transport.go:594 +0xb2
golang.org/x/net/http2.(*dialCall).dial(0xc00087d780, {0x1329a50, 0xc00019a000}, {0xc000499420, 0x19})
	/Users/richb/go/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/client_conn_pool.go:141 +0x45
created by golang.org/x/net/http2.(*clientConnPool).getStartDialLocked
	/Users/richb/go/pkg/mod/golang.org/x/net@v0.0.0-20220225172249-27dd8689420f/http2/client_conn_pool.go:134 +0x1f3
?2 goresponsiveness-
```

**Comment by hawkinsw** [comment]
I definitely do not see this behavior locally! Sorry for the trouble. I am investigating asap!

Will

**Comment by richb-hanover** [comment]
No sweat. I just try stuff, and throw reports over the wall for your amusement :-)

Let me know what other information I could provide. Thanks.

**Comment by hawkinsw** [comment]
@richb-hanover Try this!!

**Comment by hawkinsw** [comment]
> No sweat. I just try stuff, and throw reports over the wall for your amusement :-)
> 
> Let me know what other information I could provide. Thanks.

If you had not mentioned it, I *never* would have see the obvious error! Thank you *so* much!
Will

**Comment by richb-hanover** [comment]
Much Better! (I'm using a cellular hot spot, so much worse bandwidth...)

```
√ goresponsiveness-1 % docker run gorun
03-20-2022 01:05:24 UTC Go Responsiveness to mensura.cdn-apple.com:443...
Download:   8.437 Mbps (  1.055 MBps), using 20 parallel connections.
Upload:     6.812 Mbps (  0.852 MBps), using 16 parallel connections.
Total RTTs measured: 5
RPM:    53
```

**Comment by richb-hanover** [comment]
Ahah! Now I understand about the count of the RTT measurements... Am I correct that the code only starts measuring when both directions hit saturation? (I think that's the proper time to do it) Looking at the `--debug` output, it looks as if the code gets a few (5-10?) measurements of responsiveness. 

My intuition says that this is a pretty low number of samples. On the other hand, the entire setup for saturation primes the system into a worst-case state. 

Has anyone checked that the first 5-10 RTT measurements are characteristic of/similar to the next 20-50 measurements (if we maintained the traffic)? Thanks as always.

**Comment by hawkinsw** [comment]
> Ahah! Now I understand about the count of the RTT measurements... Am I correct that the code only starts measuring when both directions hit saturation? (I think that's the proper time to do it) Looking at the `--debug` output, it looks as if the code gets a few (5-10?) measurements of responsiveness.

This is exactly correct!! We only start to take those RPM checks once we have saturated the link in both directions. 

> 
> My intuition says that this is a pretty low number of samples. On the other hand, the entire setup for saturation primes the system into a worst-case state.
> 
> Has anyone checked that the first 5-10 RTT measurements are characteristic of/similar to the next 20-50 measurements (if we maintained the traffic)? Thanks as always.

This is a great question! I am going to explore this with @cpaasch and I will probably add an option to the client so that you can control that. Does that seem like a reasonable option?

Thanks again for all the contributions!!

**Comment by cpaasch** [comment]
> > Has anyone checked that the first 5-10 RTT measurements are characteristic of/similar to the next 20-50 measurements (if we maintained the traffic)? Thanks as always.
> This is a great question! I am going to explore this with @cpaasch and I will probably add an option to the client so that you can control that. Does that seem like a reasonable option?

Haven't  checked that. But I would not be surprised if there are networks where this can change. The goal of the responsiveness test is to provide a quick and dirty first estimate. But I am all for having a tool that has an option to have a longer-lasting measurement.

**Comment by richb-hanover** [comment]
Although I said I was worried/surprised by only making five RTT measurements, I wouldn't want to add an option. I hate options. [Why? They add complexity, they can break, they require documentation, they can create confusion. The --config option makes sense (I _so_ want to install a RPM server in my OpenWrt router...), --port and --path might make sense if there's a difficult RPM server.]

The RPM Tool was designed as a simple, modestly accurate ("quick and dirty") measurement. I believe we should retain that simplicity. We shouldn't move the goalpost by changing a "20 second test time."

That said, I am not opposed to a _research_ implementation that tested for diminishing returns of measuring 5, or 10, or 15, or even 50 RTT measurements. Then we can say, "We tried many variations, and 5 (or 10, or whatever) RTT measurements. Testing more didn't change the accuracy of the RPM value." 

If we think it'll matter, set a RTT count parameter, or a duration of RTT measurements in the code, but don't expose a command-line option. Thanks for listening.

**Comment by moeller0** [comment]
> Has anyone checked that the first 5-10 RTT measurements are characteristic of/similar to the next 20-50 measurements (if we maintained the traffic)? Thanks as always.

We might be able to look at the bufferbloat plots for dslreports tests here (example the downloading bufferbloat plot of [https://www.dslreports.com/speedtest/70517017?r=303](https://www.dslreports.com/speedtest/70517017?r=303)). IMHO they show that during start of the load there seems to occasionally be some transients, but after the load is established/saturating the delay timecourse (while reflecting some inner dynamics driven by e.g. ant ISP traffic shaper on the path) there does not seem to be a problem with just taking a few samples...
